// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKRwGLhKgxerESN1KehTHQRNWPKA-6nw',
    appId: '1:104760788539:web:d258c93a0234959d5abe1e',
    messagingSenderId: '104760788539',
    projectId: 'giuakydnt',
    authDomain: 'giuakydnt.firebaseapp.com',
    storageBucket: 'giuakydnt.appspot.com',
    measurementId: 'G-04XQ91NXG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeaG6i1LHdkIFSPWQ931AoiZFSJC3SOPU',
    appId: '1:104760788539:android:9b7bab2cd461ff365abe1e',
    messagingSenderId: '104760788539',
    projectId: 'giuakydnt',
    storageBucket: 'giuakydnt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5CUstw8otQXTlpAtcNV-FZh4wZDXm2I',
    appId: '1:104760788539:ios:e532d7aa381184d15abe1e',
    messagingSenderId: '104760788539',
    projectId: 'giuakydnt',
    storageBucket: 'giuakydnt.appspot.com',
    iosBundleId: 'com.example.giuakydnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR5CUstw8otQXTlpAtcNV-FZh4wZDXm2I',
    appId: '1:104760788539:ios:e532d7aa381184d15abe1e',
    messagingSenderId: '104760788539',
    projectId: 'giuakydnt',
    storageBucket: 'giuakydnt.appspot.com',
    iosBundleId: 'com.example.giuakydnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxKRwGLhKgxerESN1KehTHQRNWPKA-6nw',
    appId: '1:104760788539:web:dcabef818d1cf0805abe1e',
    messagingSenderId: '104760788539',
    projectId: 'giuakydnt',
    authDomain: 'giuakydnt.firebaseapp.com',
    storageBucket: 'giuakydnt.appspot.com',
    measurementId: 'G-PGQVTDCV92',
  );
}
